

name = "flask-app"
version = "0.1.0"

[dependencies]
python = "3.9"
flask = "1.1.4"
flask-restful = "0.3.9"
flask-cors = "3.0.10"
flask-sqlalchemy = "2.5.1"
flask-mail = "0.9.1"
flask-restx = "0.5.2"
pyjwt = "2.1.0"
